### ISSUE TITLE
🐛 Removes characters if origin has special characters

### ISSUE THREAD

**Issue by marshallku** [roum02/Fix-your-errors#20]
## Test Input

> dkssudgktpdy, cjdma qhlqrpTtmqslek.

## Expected Output

> 안녕하세요, 처음 뵙겠습니다.

## Actual Output

> 안녕하세요으겠습니다

Guess there's an issue while trying to translate special characters to korean

**Comment by roum02** [comment]
Thanks to your kindness, the issue you mentioned has been fixed.
you can test it [here](https://eg2han.xyz/) 

Thanks again!
